### ISSUE TITLE
Add custom classes to specific columns?

### ISSUE THREAD

**Issue by prateem** [Chumper/Datatable#137]
Is there any way to add custom classes to specific columns? Perhaps by using their aliases?

I know you can style specific columns by manipulating the colgroup. Here's my use case:

User clicks a button on the table, table shrinks to allow for different content div to show(). When the table shrinks, I want to hide certain columns(s) so that the table shrinks nicely and without clipping of its div/the page.

So something like

``` html
<table>
  <thead>
    <tr>
      <th class="hideWhenShrunken"> ... </th>
      <th> ... </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="hideWhenShrunken"> ... </td>
      <td> ... </td>
    </tr>
  </tbody>
</table>
```

**Comment by CalinB** [comment]
```php
Datatable::table()->setOptions([
    'aoColumns' => [
        [
            'bSortable' => false, 
            'sClass' => 'desired_class'
        ]
    ]
]);
