### ISSUE TITLE
Add class to column?

### ISSUE THREAD

**Issue by oblogic7** [Chumper/Datatable#175]
Is it possible to add a specific class to a column when using FunctionColumn?

**Comment by timgws** [comment]
@oblogic7, this needs to be done in the template.

**Comment by timgws** [comment]
@oblogic7, @CalinB commented on issue #137 that you can do the following when you render the table you can specify some options.


```php
Datatable::table()->setOptions([
    'aoColumns' => [
        ['bSortable' => true],
        ['bSortable' => false, 'sClass' => 'desired_class'],
        ['bSortable' => false]
    ]
]);
