### ISSUE TITLE
No data rendered

### ISSUE THREAD

**Issue by ghost** [Chumper/Datatable#204]
I have same problem as previous guys, I have a table only with headers, no data rendered. 
- I have jquery (1.11.1) and datatables (1.9.4) loaded before datatables' render script
- disabled all other js files 
- I have no errors on console, nor in laravel's log and php's log
- I have json result, but the sEcho is always 0:
  { aaData: [["1", "Barna", "Szalai"]] , iTotalDisplayRecords: 1, iTotalRecords: 1, sEcho: 0 }
- I've checked my nginx config, disabled temporarily rewrite rules, but nothing changes

What others should I check in your opinion? I'm out of ideas..
thanks

**Comment by khoiruddin** [comment]
@devartpro thank.. greate solution..
