### ISSUE TITLE
Can I refresh datatable after change row data (update, delete..etc) with jquery / ajax?

### ISSUE THREAD

**Issue by ghost** [Chumper/Datatable#211]
I have function to delete a row in datatable:

<script type="text/javascript">
    function deletePerfume(perfume_id) {
        if (confirm('Delete this data. Are you sure?')) {
            $.ajax({
                url: "/admin/perfumes/" + perfume_id,
                type: "DELETE",
                success: function(data, textStatus, xhr) {
                    if (xhr.status == 200) {
                        alert('Delete successful!');
                        // Refresh datatable
                    } else {
                        alert("Something's wrong. Please check again");
                    }
                },
                error: function(data, textStatus, xhr) {
                    alert("Something's wrong. Please check again");
                }
            });
        } 
    }
</script>

After delete, the alert is appear but I don't know how to refresh the datatable to update UI. Can you give me a guide please. I appreciate it. Thank you.

**Comment by timgws** [comment]
This is what I use to refresh all the datatables that are on a page (eg, when a button is clicked)

    $('.dataTable').each(function() {
        dt = $(this).dataTable();
        dt.fnDraw();
    })

I usually mix this in with a modification to the datatable:

    var additionalParameters = {};

    jQuery(document).ready(function() {
        oTable = jQuery('/**/').dataTable({
            /** Normal Datatable template... **/,
            "fnServerParams": function(aoData) {
                $.each(additionalParameters , function(k,v){
                    /** add extra parameters to the Datatable GET request **/
                    aoData.push({"name": k, "value": v});
                })
            }
        });
    });

This allows me to change the `additionalParameters` object (eg, adding new keys, changing values inside a filter).

Then, after calling `dt.fnDraw()`, the values inside `additionalParameters` will be sent to your Datatable controller.
