### ISSUE TITLE
Making Datatables fit the screen (responsive)

### ISSUE THREAD

**Issue by lozadaOmr** [Chumper/Datatable#213]
I know that Datatable somehow adds an inline css width to the table, my problem is that I need to display 8 columns and this makes the column go outside instead of squeezing the column to fit them in the screen.

I tried manually adding the bootstrap classes to the template.blade.php in the src folder but this seems to have no effect

Here is a screenshot showing the rest of the columns outside of the screen
![chumper-datatable](https://cloud.githubusercontent.com/assets/2493327/5522152/286b9924-89ee-11e4-95e4-f76ce8f02d8d.png)

Additionally I tried putting the table inside `<div class="table-responsive">` and this is the result

![chumper-responsive](https://cloud.githubusercontent.com/assets/2493327/5522234/d0ee3c86-89ef-11e4-9ce9-d81f41e9f984.png)

**Comment by ixperiencenl** [comment]
@lozadaOmr Did you already fix this prob? The problem comes from the textinputs. When you're using bootstrap, add these to the textboxes in template.blade.php:  class="form-control input-sm input-search" on line 27 if i'm correct

**Comment by lozadaOmr** [comment]
@ixperiencenl Ah unfortunately I think we just side-step on the issue and removed the custom filters. Should this issue be closed?

**Comment by ixperiencenl** [comment]
@lozadaOmr Yes, this one can be closed regarding the problem you've described. Could you send me a pm with your new solution? I'm struggling with the search issue in combination with a query...
