### ISSUE TITLE
Foundation style not working.

### ISSUE THREAD

**Issue by darkcyber** [Chumper/Datatable#234]
Hello,

Before i use Chumper Datatable my table work like expected with foundation style, but why when using chumper datatable my foundation style not working ? 
How i can fix this problem ?

Thanks, any help will be appreciated.

**Comment by thienhung1989** [comment]
Check again file config.php with option ''class' => 'table table-bordered', or 'id'...?

**Comment by darkcyber** [comment]
here is my config

        'class' => 'display responsive',

and my id 

        'id' => '',

so whats wrong dude ?

**Comment by thienhung1989** [comment]
@darkcyber  try with class: 'table table-responsive table-bordered table-striped table-hover'. 

http://www.datatables.net/manual/styling/

display datatable without Chumper/Datatable?

Chumper/Datatable: This is a laravel 4 package for the "server side" and client side of datatables at http://datatables.net/. Good luck! Close.

**Comment by darkcyber** [comment]
now it works,

don't use PagingType or sPaginationType in config file at options section , and your foundation paging style will work like expected.
