### ISSUE TITLE
How to showColumns from object

### ISSUE THREAD

**Issue by darkcyber** [Chumper/Datatable#235]
Hello,

I have problem with showColums() 

i have one to one relationships and i have alredy eager load and pass result within Datatable::collection($query)

yes i can show columns easily from first table. i can use showColumns(id) but how i can show column from second table ? in this case term_taxonomy table and description columns. i use showColumns(term_taxonomy.description) generate null  , if i use showColumns(term_taxonomy) my table show object object since term_taxonomy generate an array.

Thanks. any help will be appreciated.

**Comment by johnhatch** [comment]
You would do something like this:
```php
->showColumns('other','columns','here')
->addColumn('description',function($model){
    return $model->term_taxonomy->description;
})
```
I don't believe it's possible to access the related models columns directly from the ```showColumns()``` function. Fetching anything further than the first-level needs to be done via ```addColumn()```, I'm pretty sure, as that's how it's done [in the examples](https://github.com/Chumper/Datatable#server-example) :)

**Comment by darkcyber** [comment]
@johnhatch 

now it solved, i can get data from one to one relationships , here is the code 

    public function getCategoriesTable()
    {
        $categories = Term::with(['TermTaxonomy' => function($q){
            $q->select('term_id', 'description');
        }])->orderBy('term_id', 'desc')->get(['term_id', 'slug', 'name']);
        
        return Datatable::collection($categories)
        ->showColumns('name', 'slug')
        ->addColumn("description", function($model){
            return $model->TermTaxonomy->description;
        })
        ->addColumn("action", function($model){
            return '<a href="'.route("admin_posts_categories_destroy", $model->term_id).'" class="button small alert expand" data-method="delete" data-reveal-id="myModal'.$model->term_id.'" data-name="'.$model->name.'">Delete</a>';
        })
        ->make();
        
    }
