### ISSUE TITLE
Responsive table not working correctly

### ISSUE THREAD

**Issue by darkcyber** [Chumper/Datatable#237]
Hello, since i use this plugin my responsive table can't adapt the width, here is look like

[The screenshoot 1](http://i.imgur.com/hQ3sQXL.png)
[The screenshoot 2](http://prntscr.com/618nhj)

and my config file is

 'class' => 'display responsive',
     'id' => '',
        'options' => array(

            "sPaginationType" => "full_numbers",
            "bProcessing" => false,
            "bSort" => false,
            "responsive" => true,
        ),

then when i do some research i look into table inspect element and what i get is

    <table style="width: 691px;" aria-describedby="FGaQlQ3R_info" role="grid" id="FGaQlQ3R"    class="display responsive dataTable no-footer dtr-inline">
   
the table generate built in class "dataTable no-footer dtr-inline" and style="width 691px"
where it thus class and style come from ? 

maybe myproblem come from built in class and style.

then how to fix it ? 

Thanks a lot.

**Comment by darkcyber** [comment]
Hello,

recently i try to look into template.blade.php from chumper datatable views and hope i can change style there, but unfortunatelly i just found

    <table id="{{ $id }}" class="{{ $class }}">

in table section , so where is "style" which i say in previous comment ? i want to change it to "style=100%"

Thanks.

**Comment by Chumper** [comment]
This looks like a problem with the javascript of datatables, on the server side i am not setting any other properties for the table except the `id` and the `class`

**Comment by darkcyber** [comment]
finally i can solve by using datatables 1.10 / 1.10.4 and put this 

    "bAutoWidth" => false 

in options section in config file, and

    'class' => 'responsive',

in chumper config, don't know exactly why responsive not working with 1.9.
