### ISSUE TITLE
How to create multi table ?

### ISSUE THREAD

**Issue by darkcyber** [Chumper/Datatable#240]
Hello,

i have already setup table id in config file for delete ajax function inside the table.
yes my table and my function work like expected. 

in this case i want to create other table in other page , how i can create it with different table id ? for delete ajax purpose.

How i can do that ?

Thanks.

**Comment by darkcyber** [comment]
@Chumper sorry tagging you , may i know how i can solve my problem ? thanks.

**Comment by darkcyber** [comment]
@iftekhersunny @saqueib @jayeshmagare sorry tagging you maybe you can help me ? thanks.

**Comment by johnhatch** [comment]
You may use the ```setId()``` function to set each table's ID:
```php
Datatable::table()
->setId('testing')
```

**Comment by darkcyber** [comment]
@johnhatch
Thanks a lot.
