### ISSUE TITLE
Datatable::query with a query that has groupBy gives incorrect total row count.

### ISSUE THREAD

**Issue by timgws** [Chumper/Datatable#253]
```php
        $query = DB::table('orders')
            ->orderBy('user_id');
            ->groupBy('user_id');
```
The row count will always be the total amount of orders for the first row returned.

The query that is built is:
```sql
select count(*) as aggregate from `orders` group by `user_id`
-- this returns a row for each user_id
```

However, because of the group by, the query that is built should be:

```sql
select count(DISTINCT user_id) as aggregate from `orders`
-- the following returns only one row. the total amount of users that have orders
```

I am trying to look into an easy way to fix this issue, but so far it looks like there might not be one. It looks like extending Query\Builder and exposing the protected $groups array might be the way to go.

**Comment by timgws** [comment]
Pull requests have been merged \o/

**Comment by bytestream** [comment]
Can we get the same merged into the develop branch for Laravel 5?

I noticed there's already a ````setNoGroupByOnCount()```` function in the QueryEngine (in the develop branch) - see https://github.com/Chumper/Datatable/pull/136. That being said, this does not work if you use ````Illuminate\Database\Eloquent\Builder```` (seems to be built directly for ````Illuminate\Database\Query\Builder````)

**Comment by timgws** [comment]
@bytestream good catch, I will work on this a little later today.

**Comment by bytestream** [comment]
@timgws any news on this? I'm happy to submit a pull request resolving the issue with the Eloquent Builder in the develop branch

**Comment by timgws** [comment]
@bytestream feel free to submit a pull request. I am currently focusing my efforts at the moment on a new branch, refactoring some of the code for a new version5 branch.

If you don't do it today, I will try to get around to "soon" (I want to say after I finish work, but that might not be the case).

**Comment by timgws** [comment]
This is almost on point, @bytestream, but I would recommend splitting out all of that code to a separate function. At the moment there is code in two places that does exactly the same thing.

**Comment by bytestream** [comment]
Good point - I did this in a rush.

I'll update the pull request before I leave in a few hours

Kind regards,
Kieran Brahney

E-mail:  kieran@miami-nice.co.uk
Web:     http://www.miami-nice.co.uk
Twitter:  @KieranBrahney <https://twitter.com/KieranBrahney>

**********************************************************************
This e-mail is intended solely for the addressee and is strictly
confidential. If you are not the intended addressee, please do
not read, print, retransmit, store or act in reliance on it or any
attachments. Instead please notify me immediately and
delete the message from your computer.

E-mail transmission cannot be guaranteed to be secure or
error free and I accept no liability for changes made to this
e-mail (and any attachments) after it was sent or for viruses
arising as a result of this e-mail transmission.
**********************************************************************

**Comment by timgws** [comment]
Thank you very much for this, @bytestream
