### ISSUE TITLE
Data being received but table does not populate

### ISSUE THREAD

**Issue by RixhersAjazi** [Chumper/Datatable#26]
Hello sir,

I love the simplicity of your package. It saves me a lot of time as a developer. However I am at the end of my wits here and I need help from the creator.

I am :
-Using Query engine
-Using server side processing (->setURL(route('allUsersJson')) and  "bServerSide": true,)
-When not using server side processing my data comes just fine no issues

My controller : 

public function allUsersJson()
    {
        $user = DB::table('user');
        return Datatable::query($user)
            ->showColumns('userId', 'name', 'email', 'active', 'yearFrom', 'yearTo')
            ->searchColumns('name', 'email')
            ->make();
    }

my view : 
{{ Datatable::table()  
  ->setURL(route('allUsersJson'))
  ->addColumn('Actions','Name', 'Email', 'Status', 'From', 'To')
  ->setOptions('bProcessing', true)
  ->setOptions('bSort', false)
  ->setOptions('iDisplayLength', '5')
  ->setOptions('aLengthMenu', [5,10,15,20])
  ->setOptions('bAutoWidth', false)
  ->setOptions('sAjaxDataProp', 'aaData')
  ->render() }}

and in my chrome dev tools I send : 

Request URL:https://www.learnlaravel.com/api/users?sEcho=1&iColumns=6&sColumns=&iDisplayStart=0&iDisplayLength=5&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&sSearch=&bRegex=false...............(and so on - its a very long URL)

and I receive:

{"aaData":[["1","*****_","**_**_@gmail.com","1","08\/2012","08\/2014"],["5","RixA","**_***@gmail.com","1","02\/2012","03\/2015"]],"sEcho":0,"iTotalRecords":"2","iTotalDisplayRecords":"2"}

I don't understand what I am missing here. Any help would be great. I also asked on the laravel 4 forums as well. Thanks in advanced.

**Comment by stumped101** [comment]
Sir I am having a similar problem on wampserver apache 2.4.9 - not sure how to correct the rewrite rule and constantly getting secho of null and secho in returned json of 0. The following is my htaccess file. 
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...z
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

I would be very grateful if you could tell me how you corrected the issue you had. Many thanks
