### ISSUE TITLE
Table footer?

### ISSUE THREAD

**Issue by snipe** [Chumper/Datatable#262]
Hi there - is it currently possible to add a table footer using this package? I've checked the docs and open issues, and I don't see anything about it. I have some bulk edit buttons that need to live in a table footer, above the pagination, otherwise they're too far down and user's don't see them. 

Thanks so much in advance! Again, love this package. You've made my life so much easier.

**Comment by snipe** [comment]
(I realize you could probably handle that via the template, but wondering if there's anything built in, since I have several different views in my app.)

**Comment by thienhung1989** [comment]
->render('text of view you want') 
```php
return Datatable::table()->addColumn(array(
            trans('management-system::units.titles.id') ,
            trans('management-system::units.titles.name') ,
            trans('management-system::units.titles.short') ,
            trans('management-system::generals.titles.option') 
->rendeṛ̣('namespace..../file');

```

**Comment by snipe** [comment]
Hi @thienhung1989 - so you're suggesting doing it at the template level then?

**Comment by snipe** [comment]
I did it at the template level as suggested. It's a little less convenient, since it means I have to create a multitude of template files, but it works. Thanks, @thienhung1989!

![pug-dance](https://cloud.githubusercontent.com/assets/197404/6700301/7ef5b84c-ccc9-11e4-83f6-86f8035748b3.gif)
