### ISSUE TITLE
Individual column searching with select inputs

### ISSUE THREAD

**Issue by Mitchkoens** [Chumper/Datatable#268]
Hello Chumper,

I was wondering if you had a similar fix like the one in issue #52 that would work with select inputs instead of text inputs. 

like this https://datatables.net/examples/api/multi_filter_select.html

If you know a way how that would be great Thanks! 
I will be trying to get it to work myself but any help is appreciated.

**Comment by Bjern** [comment]
Hi

I too would like to see a working example of this.  I have used chumper (thank you very much) but am having trouble getting the column filter to work (same as above link)

My ajax url being sent to the controller is like this:
http://localhost:8080/mywebsite.com/public/admin/currentstock/datatables?sEcho=16&iColumns=9&sColumns=%2C%2C%2C%2C%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=lark&bRegex_1=true&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&mDataProp_5=5&sSearch_5=&bRegex_5=false&bSearchable_5=true&bSortable_5=true&mDataProp_6=6&sSearch_6=&bRegex_6=false&bSearchable_6=true&bSortable_6=true&mDataProp_7=7&sSearch_7=&bRegex_7=false&bSearchable_7=true&bSortable_7=true&mDataProp_8=8&sSearch_8=&bRegex_8=false&bSearchable_8=true&bSortable_8=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&sRangeSeparator=~

The search phrase is lark and its in sSearch_1

For some reason only sSearch (the search box in the header) will be used for ->searchColumns and the filters in the footer are not getting data.

Any suggestions?  What PHP would I have to add to get this to work?  Does chumper handle this?
