### ISSUE TITLE
"Illegal offset type" when testing forked repo with dev-master

### ISSUE THREAD

**Issue by rossanthony** [Chumper/Datatable#302]
```
file: "/var/www/html/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php"
line: 261
message: "Illegal offset type"
type: "ErrorException"
```

**Comment by timgws** [comment]
Hey @rossanthony, I saw this a couple of days and am currently trying to get the suite to run correctly.

@Chumper I am having issues running the suite mainly with `QueryEngineTest`.

I am trying to mock Laravel's `Config` class, but I can't seem to be able to swap the Facade class out:


        $config = Mockery::mock('ConfigMock');
        $config->shouldReceive('get')->zeroOrMoreTimes()->with("datatable::engine")->andReturn(
            array(
                'exactWordSearch' => false,
            )
        );

        Illuminate\Support\Facades\Config::swap($config);

**Comment by ErichNiem** [comment]
Hi

I do not know what you guys are talking about, but I just did a composer update and I am getting this same offset error with all the tables I created previously

**Comment by timgws** [comment]
@ErichNiem what was the last time you updated that worked?

**Comment by timgws** [comment]
Actually, could both of you check out this change:

https://github.com/timgws/Datatable/commit/ed4617799f22cf974d8973668df29c794090347b

and see if it fixes the problem(s) for you?

**Comment by ErichNiem** [comment]
@timgws I haven't updated for a while, the last version I had was 1.9 I will try your fix and get back to you

**Comment by ErichNiem** [comment]
@timgws 

Yes is working fine now

Thank you

**Comment by timgws** [comment]
@ErichNiem thanks for checking that out. @Chumper should merge this soon!

**Comment by timgws** [comment]
:+1: @ErichNiem @rossanthony, could you please try running `composer update Chumper/Datatable` and see if that fixes your problems?

**Comment by ErichNiem** [comment]
Sorry to take so long, composer update done. All Good!!
