### ISSUE TITLE
Method Illuminate\View\View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by TheTechnoMan** [Chumper/Datatable#307]
Hey,

just did a composer update and now there seems to be an issue with outputting the javascript code inside the blade template, it always throws this exception:

Method Illuminate\View\View::__toString() must not throw an exception

This line is causing the issue:

```{!! $table->script() !!}```

Any idea what is going on? Can't find what is causing the issue, it also worked fine before the update. I'm on L5.

It also happens when I remove the noScript(); now it shows the error when trying to render the table:

```{!! $table->render() !!}```

Thanks

**Comment by mgsmus** [comment]
You have to publish assets again. Do not forget backup up current config/chumper.datatable.php and resources/views/vendor/chumper.datatable/ first.

**Comment by TheTechnoMan** [comment]
thanks!

**Comment by hamedmohammadi** [comment]
in my experience the issue was old cached files after updating chumper/datatable.
 remove all files in app/storage/views
