### ISSUE TITLE
class datatable not found in laravel 5 development branch package

### ISSUE THREAD

**Issue by rfh103** [Chumper/Datatable#314]
I am trying to port my existing application from laravel 4 to 5 I have installed the dev application and updated providers and aliases as per the docs but in my controllers folder I get the error 

Class 'App\Http\Controllers\Datatable' not found

any ideas ? thanks

**Comment by timgws** [comment]
@rfh103, I assume this was just a namespace issue?

Did you manage to get Datatable up and running on Laravel 5?

**Comment by rfh103** [comment]
@timgws indeed it was just a namespace issue all fixed now thanks
