### ISSUE TITLE
Eloquent does not populate correct rows in datatable

### ISSUE THREAD

**Issue by stumped101** [Chumper/Datatable#321]
I am having a problem with populating the datatable correctly from an associative array - (in my example $chosenPlants). This datatable is being populated from another one being used as a form - hence `Input:all()`. The array is correct and `print_r( Plant::whereIn('id', $chosenPlants)->get());` appears to return the correct rows. However when the new datatable is populated it is done so with data from the FIRST page of the original datatable form. I would greatly appreciate any help on this. My code is as follows:

    Route::get('chosenPlants', function(){
        $chosenPlants = Input::all();
    	//print_r( Plant::whereIn('id', $chosenPlants)->get());
        if(Datatable::shouldHandle())
        {

            return Datatable::collection(Plant::whereIn('id', $chosenPlants)->get())
            ->showColumns( 'Plant_name', 'Common_name','Htmin', 'Htmax',
                                'Pmin', 'Pmax', 'root', 'girthmin', 'girthmax', 'Price')
            ->searchColumns( 'Plant_name', 'Common_name','Htmin', 'Htmax',
                    'Pmin', 'Pmax', 'root', 'girthmin', 'girthmax')
            ->addColumn('Price', function($model){
                    $temp = Price::where('p_id', $model->id)->pluck('maxprice');
                    $temp2 = str_replace("€", "", Price::where('p_id', $model->id)->pluck('maxprice'));
                    return $temp2;
                    })
            ->orderColumns( 'Plant_name', 'Common_name','Htmin', 'Htmax',
                    'Pmin', 'Pmax', 'root', 'girthmin', 'girthmax')
            ->make();

        }
        return View::make("displayViews.chosenPlants");

    });

**Comment by stumped101** [comment]
I have checked my JSON and it is correct. Instead of my array($chosenPlants) I substituted array(1,2,3) and this worked correctly i.e. populated resulting datatable correctly. However as soon as I put $chosenPlants back into the line "return Datatable::collection(Plant::whereIn('id', $chosenPlants)->get())" the datatable renders the first page of the original form from which it was called (itself another datatable). This is very bizarre behaviour that I cannot understand - any thoughts on this one?

**Comment by stumped101** [comment]
This has become an obstacle that I need to resolve. If I cannot resolve this problem I will soon  have to use an alternative which is a pity as up to this chumper has worked reasonably well for me.

**Comment by stumped101** [comment]
Problem appears to be that the datatable is called TWICE  - once with the correct data and again with incorrect data why is this happening?

**Comment by stumped101** [comment]
Once again the lack of support documentation & response to my query on this plugin is very dissappointing.

**Comment by timgws** [comment]
@stumped101, as you are not paying anyone for support, I would not get so angry that no one has jumped to help you.

What is the difference between a `dd($chosenPlants)` and a `dd(array(1,2,3,))`?. What is the query string that is being sent to the Datatable? This has not been provided, and makes it difficult to debug the issue.

`$chosenPlants = Input::all();` most likely is also pulling in a bunch of query data for the datatable as well, which might be causing issues.

**Comment by stumped101** [comment]
Thanks for your response: 

(code extract)

$cp = array();
$cp = array_values(Input::all());
unset($cp[0]);
$result =  Plant::whereIn('id', $cp)->get();
		
OUTPUT
-----------------------------------
dd($cp);
array (size=3)
  1 => string '14902' (length=5)
  2 => string '14905' (length=5)
  3 => string '3' (length=1)
dd($result);

object(Illuminate\Database\Eloquent\Collection)[232]
  protected 'items' => 
    array (size=4)
      0 => 
        object(Plant)[227]
          protected 'connection' => null
          protected 'table' => null
          protected 'primaryKey' => string 'id' (length=2)
          protected 'perPage' => int 15
          public 'incrementing' => boolean true
          public 'timestamps' => boolean true
          protected 'attributes' => 
            array (size=12)
              ...
          protected 'original' => 
            array (size=12)
              ...
          protected 'relations' => 
            array (size=0)
              ...
          protected 'hidden' => 
            array (size=0)
              ...
          protected 'visible' => 
            array (size=0)
              ...
          protected 'appends' => 
            array (size=0)
              ...
          protected 'fillable' => 
            array (size=0)
              ...
          protected 'guarded' => 
            array (size=1)
              ...
          protected 'dates' => 
            array (size=0)
              ...
          protected 'touches' => 
            array (size=0)
              ...
          protected 'observables' => 
            array (size=0)
              ...
          protected 'with' => 
            array (size=0)
              ...
          protected 'morphClass' => null
          public 'exists' => boolean true
      1 => 
        object(Plant)[228]
          protected 'connection' => null
          protected 'table' => null
          protected 'primaryKey' => string 'id' (length=2)
          protected 'perPage' => int 15
          public 'incrementing' => boolean true
          public 'timestamps' => boolean true
          protected 'attributes' => 
            array (size=12)
              ...
          protected 'original' => 
            array (size=12)
              ...
          protected 'relations' => 
            array (size=0)
              ...
          protected 'hidden' => 
            array (size=0)
              ...
          protected 'visible' => 
            array (size=0)
              ...
          protected 'appends' => 
            array (size=0)
              ...
          protected 'fillable' => 
            array (size=0)
              ...
          protected 'guarded' => 
            array (size=1)
              ...
          protected 'dates' => 
            array (size=0)
              ...
          protected 'touches' => 
            array (size=0)
              ...
          protected 'observables' => 
            array (size=0)
              ...
          protected 'with' => 
            array (size=0)
              ...
          protected 'morphClass' => null
          public 'exists' => boolean true
      2 => 
        object(Plant)[233]
          protected 'connection' => null
          protected 'table' => null
          protected 'primaryKey' => string 'id' (length=2)
          protected 'perPage' => int 15
          public 'incrementing' => boolean true
          public 'timestamps' => boolean true
          protected 'attributes' => 
            array (size=12)
              ...
          protected 'original' => 
            array (size=12)
              ...
          protected 'relations' => 
            array (size=0)
              ...
          protected 'hidden' => 
            array (size=0)
              ...
          protected 'visible' => 
            array (size=0)
              ...
          protected 'appends' => 
            array (size=0)
              ...
          protected 'fillable' => 
            array (size=0)
              ...
          protected 'guarded' => 
            array (size=1)
              ...
          protected 'dates' => 
            array (size=0)
              ...
          protected 'touches' => 
            array (size=0)
              ...
          protected 'observables' => 
            array (size=0)
              ...
          protected 'with' => 
            array (size=0)
              ...
          protected 'morphClass' => null
          public 'exists' => boolean true
      3 => 
        object(Plant)[234]
          protected 'connection' => null
          protected 'table' => null
          protected 'primaryKey' => string 'id' (length=2)
          protected 'perPage' => int 15
          public 'incrementing' => boolean true
          public 'timestamps' => boolean true
          protected 'attributes' => 
            array (size=12)
              ...
          protected 'original' => 
            array (size=12)
              ...
          protected 'relations' => 
            array (size=0)
              ...
          protected 'hidden' => 
            array (size=0)
              ...
          protected 'visible' => 
            array (size=0)
              ...
          protected 'appends' => 
            array (size=0)
              ...
          protected 'fillable' => 
            array (size=0)
              ...
          protected 'guarded' => 
            array (size=1)
              ...
          protected 'dates' => 
            array (size=0)
              ...
          protected 'touches' => 
            array (size=0)
              ...
          protected 'observables' => 
            array (size=0)
              ...
          protected 'with' => 
            array (size=0)
              ...
          protected 'morphClass' => null
          public 'exists' => boolean true


dd(array(1,2,3)):

array (size=3)
  0 => int 1
  1 => int 2
  2 => int 3

**Comment by stumped101** [comment]
Clearly this plugin is not designed for large tables. While it had some good features the lack of supporting documentation is a major drawback - I have no choice but to uninstall and use another plugin instead.

**Comment by thienhung1989** [comment]
hi @stumped101, this project can work with big data. You just need try with query. 
1. Optimal code with query before use `Chumper.Datatable` (orderby, groupby, ....)
2. Avoid all data edit by `collection`:
 ```
->addColumn('Price', function($model){
     ....
})
->orderColumns(...)
```
3. Last, use collect too many is bad.

If you want reuse package, you just change all collect -> query, optimal before use Datatable:....
Good luck to you.
