### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by carlituxman** [Chumper/Datatable#323]
Still waiting for laravel 5 version (only develop branch). Now is released Laravel 5.1

some news about package for this version?

**Comment by timgws** [comment]
The develop branch is most likely going to sit there for a while, until the quality of the code base improves.

Does the develop branch not work for you at the moment?

**Comment by timgws** [comment]
A Laravel 5 package is close to being completed. To install it:

    composer require chumper/datatable "dev-version3"

If you find any issues, please report them in the bug tracker!
