### ISSUE TITLE
order columns

### ISSUE THREAD

**Issue by carlituxman** [Chumper/Datatable#329]
The alphabetically order not works, I have a column name and when I order by this column the order is not alphabetically.

what can be the problem?

the order is only by ID

**Comment by timgws** [comment]
Can you please show what the Datatable ajax endpoint looks like? Maybe it's not in `orderColumns`?

        public function getDatatable()
        {
            return Datatable::collection(User::all(array('id','name')))
            ->showColumns('id', 'name')
            ->searchColumns('name')
            ->orderColumns('id','name')
            ->make();
        }

**Comment by carlituxman** [comment]
I have: 

public function getIndex()
    {
        if(Datatable::shouldHandle())
        {
             return Datatable::collection(MyModel::all())
                ->showColumns('id', 'name')
                ->searchColumns('name')
                ->orderColumns('id','name')
                ->make();
        }

        return view('admin.index');
    }

and in the view:

{!! Datatable::table()
                ->addColumn('ID','Name')
                ->setUrl( route('admin.index') )
                ->render() !!}

When I order by column Name, it order by ID

**Comment by carlituxman** [comment]
If I use: return Datatable::collection(MyModel::orderBy('name')->get())
it works ordering by name, but if add another orderColumns for example:
->orderColumns('id','name','lastname') and try order by lastname the order continue remains the initial (name asc or desc)

**Comment by timgws** [comment]
OK, thanks for letting me know. I am going to look into this in a second.

**Comment by carlituxman** [comment]
something new about this?

**Comment by MoaazGouda** [comment]
i have the same issue here, it orders by id only
@carlituxman @timgws any updates?

thanks.

**Comment by timgws** [comment]
Hey everyone,
I am going to be sorting this out in a couple of hours.
Cheers,Tim




---- On Sat, 05 Sep 2015 04:22:11 +1000 notifications@github.com wrote ---- i have the same issue here, it orders by id only

@carlituxman @timgws any updates?
thanks.

**Comment by timgws** [comment]
@MoaazGouda, @carlituxman this issue is now fixed.

**Comment by carlituxman** [comment]
There any way to set all columns for sorting? like '*' for example?

**Comment by timgws** [comment]
Consider it done!

**Comment by MoaazGouda** [comment]
:+1:
