### ISSUE TITLE
Broken Dependencies on develop branch

### ISSUE THREAD

**Issue by Javier-Rotelli** [Chumper/Datatable#337]
Hello:
I'm trying to work on the develop branch. on composer install i get this error:
https://gist.github.com/Javier-Rotelli/7b994ef0c11717c88d0b

This line is causing it:

`"orchestra/testbench": "2.1.*"`
changing it to:
`"orchestra/testbench": "3.1.*"`
fixes the problem

**Comment by timgws** [comment]
Thanks for reporting this. This is now fixed.
