### ISSUE TITLE
Chumper/Datatable tests are broken

### ISSUE THREAD

**Issue by Javier-Rotelli** [Chumper/Datatable#341]
i can't run the tests. 
when i do
`phpunit` i get the following errors:
https://gist.github.com/Javier-Rotelli/80656d7ac5db694c7d38

anyone has the tests running? 
if not. should i continue working on fixing them and make a pull request?

**Comment by timgws** [comment]
I would love for you to continue working on fixing them and make a pull request.

**Comment by Javier-Rotelli** [comment]
@timgws could you please look at this https://github.com/MG-Web/Datatable/commit/f81a91ca6c2d0a1785d240777a200e4d92f65434 ?

I added a method called `getViewParameters` wich returns the array of parameters that would be passed to the view. with that, i do an assert to verify that it is allright. 
it works, but i'm not sure about it...

**Comment by timgws** [comment]
Looks good to me, @Javier-Rotelli. Let me have a look at it properly over the next couple of days and I will merge it in.

**Comment by Javier-Rotelli** [comment]
@timgws great!  i'll make a pull request

**Comment by Javier-Rotelli** [comment]
shouldn't this be closed? the tests are running now

**Comment by timgws** [comment]
Yes! Thanks @Javier-Rotelli
