### ISSUE TITLE
L5 - Collection Engine Individual Column Search

### ISSUE THREAD

**Issue by bytestream** [Chumper/Datatable#342]
Currently the ````CollectionEngine```` in the ````develop```` branch seems to only support column searches using the __universal__ ````sSearch```` parameter (see [doInternalSearch()](https://github.com/Chumper/Datatable/blob/develop/src/Chumper/Datatable/Engines/CollectionEngine.php#L129)). I'm not sure why this is as the L4 (master) branch supports individual column searching, see [here](https://github.com/Chumper/Datatable/blob/master/src/Chumper/Datatable/Engines/CollectionEngine.php#L140).

**Test Case**

* Search on the first column using the ````sSearch_0```` param. For example: 
````
http://localhost/datatables/2/article?sEcho=2&iColumns=8&sColumns=,,,,,,,&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=test&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&mDataProp_5=5&sSearch_5=&bRegex_5=false&bSearchable_5=true&bSortable_5=true&mDataProp_6=6&sSearch_6=&bRegex_6=false&bSearchable_6=true&bSortable_6=true&mDataProp_7=7&sSearch_7=&bRegex_7=false&bSearchable_7=true&bSortable_7=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&_=1444486241784
````
* Results aren't filtered

**Comment by timgws** [comment]
Thanks @bytestream
