### ISSUE TITLE
CollectionEngine Ordering

### ISSUE THREAD

**Issue by bytestream** [Chumper/Datatable#344]
I'm not sure whether this is intentional but internal ordering on the collection engine makes use of natural ordering (how a human would), see [line 267](https://github.com/Chumper/Datatable/blob/develop/src/Chumper/Datatable/Engines/CollectionEngine.php#L267).

Natural ordering alone doesn't work great when using case-sensitive data. See [test case](http://codepad.viper-7.com/YDqUMH).

If you agree that this would be a beneficial change I'll submit a pull request combining SORT_NATURAL with the [SORT_FLAG_CASE](http://php.net/manual/en/function.sort.php) constant.

**Comment by timgws** [comment]
@bytestream I agree, however, I think the ordering flags for the collection should be specified as an option, rather then being hard coded.

**Comment by bytestream** [comment]
@timgws see PR https://github.com/Chumper/Datatable/pull/349

**Comment by timgws** [comment]
Merged w/ PR #349
