### ISSUE TITLE
iTotalRecords not correct

### ISSUE THREAD

**Issue by Bjern** [Chumper/Datatable#353]
Hi

Firstly Tx for a great product.

I am having some trouble getting my datatable to show the correct number of records and as a consequence the correct pagination.

Here is my code:

        $startdate = date("Y-m-d", strtotime('-3 months'));
        $enddate = date("Y-m-d");
        
        $soh = DB::table('warehousestock_movement')
            ->select(DB::raw('Sum(warehousestock_movement.itemqty) as Sum_itemqty'))
            ->whereRaw("warehousestock_movement.transact_date <= '".$startdate."'")
            ->whereRaw('warehousestock_movement.fk_inventory_id = inventory.id')
            ->groupBy('warehousestock_movement.fk_inventory_id');
        
        $checkin = DB::table('warehousestock_movement')
            ->select(DB::raw('Sum(warehousestock_movement.itemqty) as Sum_itemqty'))
            ->whereRaw("warehousestock_movement.transact_date > '".$startdate."'")
            ->whereRaw("warehousestock_movement.transact_date <= '".$enddate."'")
            ->whereRaw('warehousestock_movement.itemqty > 0')
            ->whereRaw('warehousestock_movement.fk_inventory_id = inventory.id')
            ->groupBy('warehousestock_movement.fk_inventory_id');
            
        $checkout = DB::table('warehousestock_movement')
            ->select(DB::raw('Sum(warehousestock_movement.itemqty) As Sum_itemqty'))
            ->whereRaw("warehousestock_movement.transact_date >= '".$startdate."'")
            ->whereRaw("warehousestock_movement.transact_date <= '".$enddate."'")
            ->whereRaw('warehousestock_movement.itemqty < 0')
            ->whereRaw('warehousestock_movement.fk_inventory_id = inventory.id')
            ->groupBy('warehousestock_movement.fk_inventory_id');
            
		// first get the records
		$stock = DB::table('warehousestock_movement')
		->select('inventory.id','inventory.name as inventory','clients.name as client','brands.name as brand',
                'inventory.barcode as barcode', 
                
            //Get the stock on hand at start date    
            DB::raw("({$soh->toSql()}) as SOH"),
             
            //Sum all receipts between start and end date
            DB::raw("({$checkin->toSql()}) as checkin"),
            
            //Sum all dispatches between start and end date 
            DB::raw("({$checkout->toSql()}) as checkout"),
            
            'inventory.fk_client_id',
            'warehousestock_movement.fk_inventory_id')
		->join('inventory', 'warehousestock_movement.fk_inventory_id', '=', 'inventory.id')
        ->join('clients', 'inventory.fk_client_id', '=', 'clients.id')
		->join('brands', 'inventory.fk_brand_id', '=', 'brands.id')
        ->where(function($query)
        {
            $user = Sentry::getUser();
            $userClient = User::find($user->id)->userclient;
        
            if ($userClient) {
            
                $clients = Clients::find($userClient->fk_client_id);
                
                    if($clients->name != 'Select one...'){
                        $query->where('inventory.fk_client_id','=', $userClient->fk_client_id);
                    }                                
            }                       
        })
		->groupBy('warehousestock_movement.fk_inventory_id');
    
		// return a datatable of results in json
		$data = Datatable::query($stock)
		->showColumns('client','brand','inventory','barcode','SOH', 'checkin', 'checkout', 'rate')
		->addColumn('rate', function($model)
		{
			$total = $model->SOH + $model->checkin;
            if ($model->checkout)
            {
			    $rate = round((abs($model->checkout) / $total) * 100)."%";
            }
            else
            {
			    $rate = " ";
            }
			return $rate;            
		})
		->orderColumns('client','brand','inventory', 'barcode', 'SOH', 'checkin', 'checkout')
		->searchColumns('clients.name','brands.name','inventory.name', 'barcode')
		->make();

		return $data;

Can anyone help as to why its showing this (below).  There are 10 records here requested by pagination BUT it shows a iTotal of 3 records.  If I switch to 25 or 100 i get them but the total always stays on 3 causing the < 1 2 3 > buttons to be disabled.

{"aaData":[["AstraZeneca ","Asthma","Asthma Triggers A4 Pads Option 2 ","20151007AST002",null,"85",null," "],["AstraZeneca ","Exacebation","Exacebation Card","20150618AST009","2999","2101",null," "],["AstraZeneca ","AZ Generic","Symbicord COPD Competitor Card","20150929AST005","5000",null,null," "],["AstraZeneca ","SSA AZ","SSA AZ Corporate A4 Notepads","20150618AST004","4015",null,null," "],["AstraZeneca ","Symbicord","Symbicord Control Card","20150618AST051","2649","23851",null," "],["AstraZeneca ","Pulmi Promo Material","Pulmi Promo Material- Nebs Dosage","20150618AST058","200",null,null," "],["AstraZeneca ","SA Onglyza","SA Onglyza box","20150617AST003","156",null,null," "],["AstraZeneca ","Symbicord","Symbicord Patient Profile Tom","20150618AST039","2349",null,null," "],["AstraZeneca ","Pulmicort","Pulmicort Patient Leaflet","20150618AST070","16999",null,null," "],["AstraZeneca ","Vimovo","Vimovo Pain Ruler","20150618AST018","0",null,null," "]],"sEcho":3,"iTotalRecords":3,"iTotalDisplayRecords":3}

**Comment by timgws** [comment]
Hi @Bjern,

A quick search for "Group By" in this repository would have pointed you here: https://github.com/Chumper/Datatable/issues/253

Basically, when your DB query has a group by (for example)

```php
        $query = DB::table('orders')
            ->orderBy('user_id');
            ->groupBy('user_id');
```
The row count will always be the total amount of orders for the first row returned.

The query that is built is:
```sql
select count(*) as aggregate from `orders` group by `user_id`
-- this returns a row for each user_id
```

However, because of the group by, the query that is built should be:

```sql
select count(DISTINCT user_id) as aggregate from `orders`
-- the following returns only one row. the total amount of users that have orders
```

The patch on the issue talks about count issues.

An option has been added to the code (`noGroupByOnCount`) which will remove the GROUP BY's (if there are any).

```php
    $data = Datatable::query($stock)
    ->showColumns('client','brand','inventory','barcode','SOH', 'checkin', 'checkout', 'rate')
    ->addColumn('rate', function($model)
    {
        $total = $model->SOH + $model->checkin;
        if ($model->checkout)
        {
            $rate = round((abs($model->checkout) / $total) * 100)."%";
        }
        else
        {
            $rate = " ";
        }
        return $rate;            
    })
    ->orderColumns('client','brand','inventory', 'barcode', 'SOH', 'checkin', 'checkout')
    ->searchColumns('clients.name','brands.name','inventory.name', 'barcode')
    //// 
    //// NOTE THIS NEXT LINE BEING ADDED!
    //// 
    ->setNoGroupByOnCount()
    ->make();

    return $data;
```

This should return correct row counts. If not, please let me know!

**Comment by Bjern** [comment]
I get this:

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
HELP
Call to undefined method Chumper\Datatable\Engines\QueryEngine::setNoGroupByOnCount()

I'm guessing we're talking about different versions of Chumper.  I am using Laravel 4.2 with Chumper required:

"chumper/datatable": "2.*",

Any suggestions?  Tx for the informative answer, I never thought to look at the groupby as the problem.

**Comment by timgws** [comment]
No, there is no need to update to the dev version (it's for Laravel 5).

Update to `dev-master`.

**Comment by Bjern** [comment]
Thank you.  I have updated to master and the laravel no longer gives an error on ->setNoGroupByOnCount()  I also now have some pagination of the results.  However I have 215 results returned and now it shows 400...

"iTotalRecords":400,"iTotalDisplayRecords":400

It may have something to do with those sub queries.  At least I can demo to the client but if they click on pages 22-40 there are no results.

**Comment by timgws** [comment]
Interesting. @Bjern could you please email me the SQL query that you get *before* running `Datatable::query`?

```php
echo $stock->toSql()
```

**Comment by Marian0** [comment]
I'm having the same issue, using Laravel 4.2.

```
$query = User::query();
        $query->select(['users.*', DB::raw('max(events.created_at) as last_visit_at')]);

        $query->withTrashed();

        $query->join('events', function($join) use ($date) {
            $join->on('users.id', '=', 'events.user_id');
            $join->where('events.created_at', 'LIKE', "%{$date}%");
        });

        $query->groupBy('users.id');
```

I got results but just first page with wrong iTotalRecords :

```
"sEcho": 7,
"iTotalRecords": 1,
"iTotalDisplayRecords": 1
```

Any idea about solving this ?

Thanks
