### ISSUE TITLE
error exception version5

### ISSUE THREAD

**Issue by carlituxman** [Chumper/Datatable#355]
I've migrated to dev-version5 and I received this error in front-end:
DataTables warning: table id=83OafNWh - Ajax error. For more information about this error, please see http://datatables.net/tn/7

at logs I have:
exception 'ErrorException' with message 'Undefined variable: input' 
in .../vendor/chumper/datatable/src/Chumper/Datatable/InputEngine.php:49

**Comment by timgws** [comment]
As per #354, If you are using Laravel 5:

    composer require chumper/datatable "dev-develop"

If you are using Laravel 4:

    composer require chumper/datatable "dev-master"
