### ISSUE TITLE
How to use chumper datatable to show values from an array

### ISSUE THREAD

**Issue by mverma16** [Chumper/Datatable#360]
I have to read names of the files present in some specific folder in laravel package (from resources/lang folder to check available languages) and then show these names in the datatable. I am able to read the names of available folders in resources/lang using scandir($directory) and I am storing these names in an array. I am using chumper datatable and I have to show these array values in that table. But I can not do that because I don't know how to populate chumper datatable without using database query. Can anyone tell me how to do it.

**Comment by Chumper** [comment]
Use the `CollectionEngine` and create a new `Collection`:
```php
Datatable::collection(new Collection(<your array>))->...
```

**Comment by mverma16** [comment]
Thanks but can you be more specific. I tried it but getting ajax error.

**Comment by mverma16** [comment]
Thanks but can you be more specific. Which method should I use? I am also getting an ajax error.
