### ISSUE TITLE
Multi Column Filtering

### ISSUE THREAD

**Issue by MarlonEtiene** [Chumper/Datatable#52]
Hello again!

Have any chances to have multi column filtering like this

http://www.datatables.net/examples/api/multi_filter.html

Thanks!

**Comment by weiloon1234** [comment]
Hello, i know this is working at laravel 4 but i tried in laravel 5 it didn't work, what i've tried is edit the javascript template to be like this, but getting error

    Uncaught TypeError: this.api(...).columns(...).every is not a function

    jQuery(document).ready(function () {
            var options = {!! $options !!};
            options.initComplete = function() {
                this.api().columns().every( function () {
                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                );

                                column
                                        .search( val ? '^'+val+'$' : '', true, false )
                                        .draw();
                            } );

                    column.data().unique().sort().each( function ( d, j ) {
                        select.append( '<option value="'+d+'">'+d+'</option>' )
                    } );
                } );
            };
            // dynamic table
            var oTable = jQuery('#{{ $id }}').dataTable(options);
    });
